# Generated by Django 4.1.7 on 2023-04-01 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_team_logo_teamcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterModelOptions(
            name='teamcategory',
            options={'verbose_name_plural': 'Team Categories'},
        ),
    ]
