# Generated by Django 4.1.7 on 2023-04-01 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_away_team_logo_match_home_team_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
    ]
