# Generated by Django 4.1.7 on 2023-04-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_news_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='article',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
