# Generated by Django 4.1.7 on 2023-04-01 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('position', models.CharField(max_length=200)),
                ('jersey_number', models.IntegerField()),
                ('foot', models.CharField(choices=[('Right', 'Right'), ('Left', 'Left'), ('Both', 'Both')], max_length=200)),
                ('club', models.CharField(blank=True, default='Vipers SC', max_length=200, null=True)),
                ('transfer_value', models.IntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('awards', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('yellow_cards', models.IntegerField()),
                ('red_cards', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
        ),
    ]
