# Generated by Django 4.1.7 on 2023-04-01 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_rename_statistics_playerstatistics_player_team_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name_plural': 'Player'},
        ),
        migrations.AlterModelOptions(
            name='playerstatistics',
            options={'verbose_name_plural': 'Player Statistics'},
        ),
    ]
