# Generated by Django 4.1.7 on 2023-04-01 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('VIP', 'VIP'), ('ORDINARY', 'ORDINARY'), ('STUDENT', 'STUDENT'), ('VVIP', 'VVIP')], max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ticket_holder_allocation', models.CharField(choices=[('SEASONAL', 'SEASONAL'), ('SPONSORS', 'SPONSORS'), ('SPECIAL', 'SPECIAL'), ('PROMOTIONAL', 'PROMOTIONAL'), ('GENERAL', 'GENERAL')], max_length=200)),
                ('seat_number', models.IntegerField()),
                ('availability_status', models.BooleanField(default=True)),
                ('barcode', models.CharField(blank=True, max_length=200, null=True)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('date_sold', models.DateField(blank=True, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
            ],
        ),
    ]
