# Generated by Django 4.1.7 on 2023-04-01 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
